blueprint:
  name: Luftreiniger Auto-Schaltung (Mehrfach)
  description: |
    <br>
    <b>📘Dieser Blueprint schaltet mehrere Luftreiniger nach Entitäten, Schaltern oder manuellen Schaltern am Gerät ein und automatisch wieder aus. Zeitversatz nachdem die Aktion ausgeführt wird liegt bei 3min.</b>
    <br><br>
    📅 <b>Schalter, Entitäten, Bereiche</b>: Luftreiniger werden nach Schalter, Entitäten oder Bereichen eingeschaltet und nach gesetztem Luftwert automatisch wieder abgeschaltet.<br>
    ⏰ <b>Automatische Abschaltung</b>: Luftreiniger werden nach gesetztem Luftwert und manueller Auslösung am Gerät automatisch wieder abgeschaltet.
  domain: automation
  input:
    manual_toggle:
      name: Schalters bzw. Entität
      description: Schalter o. Entität, um Luftreiniger manuell zu aktivieren Abschaltung automatisch).
      selector:
        entity:
          domain: 
            - input_boolean
            - switch
            - light
            - fan
            - binary_sensor
    manual_toggle_state:
      name: Zustand des Schalters bzw. der Entität
      description: Zustand, bei dem die Automatisierung ausgelöst wird (on oder off)
      default: "on"
      selector:
        select:
          options:
            - "on"
            - "off"
    pm2_5_sensor:
      name: PM2.5 Sensor
      description: PM2.5 Sensor für die Luftreiniger
      selector:
        entity:
          domain: sensor
    ppm_threshold:
      name: PM2.5 Grenzwert
      description: Grenzwert (PPM) für das Abschalten der Luftreiniger
      default: 50
      selector:
        number:
          min: 1
          max: 120
          step: 1
    fan_entities:
      name: Luftreiniger
      description: Entitäten, Bereiche oder Geräte der gewünschten Luftreiniger
      selector:
        target:
          entity:
            domain: fan

trigger:
  - platform: state
    entity_id: !input pm2_5_sensor
    id: autooff
  - platform: state
    entity_id: !input manual_toggle
    to: !input manual_toggle_state
    id: manual

condition: []

action:
  - choose:
      # Automatische Steuerung basierend auf PM2.5
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'autooff' }}"
        sequence:
          - delay:
              minutes: 3  # 3 Minuten warten, um den realen PM2.5-Wert zu ermitteln
          - condition: numeric_state
            entity_id: !input pm2_5_sensor
            below: !input ppm_threshold  # Prüfen, ob der PM2.5-Wert unter dem Grenzwert liegt
          - service: fan.turn_off
            target: !input fan_entities
      # Manuelle Steuerung
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'manual' }}"
        sequence:
          - service: fan.turn_on
            target: !input fan_entities
          - delay:
              minutes: 3  # 3 Minuten warten, um den realen PM2.5-Wert zu ermitteln
          - condition: numeric_state
            entity_id: !input pm2_5_sensor
            below: !input ppm_threshold  # Prüfen, ob der PM2.5-Wert unter dem Grenzwert liegt
          - service: fan.turn_off
            target: !input fan_entities

mode: single
